# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
domain: thanhlongb.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://thanhlongb.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /      # place folder name if the site is served in a subfolder   
title: Bùi Thành Long (thanhlongb)
email: thanhlongb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
plainwhite:
  name: Bui Thanh Long
  tagline: RMIT University's Student
  date_format: "%b %-d, %Y"
  portfolio_image:  "assets/myface.jfif" # the path from the base directory of the site to the image to display (no / at the start)

  social_links:
    github: thanhlongb
    linkedIn: in/thanhlongb # format: locale/username
# github_username:  thanhlongb

# Build settings
markdown: kramdown
remote_theme: samarsault/plainwhite-jekyll
# theme: minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
